### ISSUE TITLE
Add Free Peoples

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#297] opened 2019-08-26 02:33 UTC

**Comment by Zirhark** [comment] 2019-08-29 20:49
It should probably be called Cities of Sigmar instead of free peoples.  Rumor is we should know more next week for release time frame. I will let you know if I pick up the book to get it created.

**Comment by daviseford** [comment] 2019-09-14 15:00
There isn't currently a Battletome for Free Peoples.

The Grand Alliance Order book has all the Warscrolls and Battalions.
This should be supplemented with the Grand Alliance Order Errata and Designers' Commentary from the FAQs.
Allegiance Abilities are in the General's Handbook 2018.
Matched play points are in the General's Handbook 2018.
Alternatively up to date Warscrolls can be found in the WH AoS app.
The Generals Handbook 2019 includes the current Allegiance abilities for the Free Peoples faction.

**Comment by JohnSchramm** [comment] 2019-09-24 14:33
Duplicate of #453

**Closed** 2019-09-24 14:38 UTC
Labels: help wanted, new army
